providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs_20"]

[variables]
COREPACK_INTEGRITY_KEYS = "0"

[phases.install]
cmds = ["corepack enable pnpm", "pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "pnpm start"
