"use client";

/**
 * EmpresaReportes — Report generator for empresa admin (new feature).
 *
 * Two report types, each with their own period selector and export format choice:
 *
 *  1. Usuarios nuevos  — rows: nombre, email, teléfono, rol, tipo_cuenta,
 *                               estado, fecha_registro
 *     Source: supabase.from('users').select(...).gte/lte on created_at
 *     RLS users_empresa_admin_read scopes to empresa automatically.
 *
 *  2. Citas
 *     a) Por servicio — rows: servicio, total_citas
 *     b) Por titular  — rows: titular, citas_propias, citas_familiares, total
 *     Source: supabase.from('citas').select(paciente join) .gte/lte on fecha_hora_cita
 *     RLS citas_empresa_admin_read scopes automatically.
 *
 * Export: .xlsx  (SheetJS) / .csv  (SheetJS sheet_to_csv + UTF-8 BOM)
 */

import { useState, useEffect, useCallback } from "react";
import { useTranslations } from "next-intl";
import { toast } from "sonner";
import * as XLSX from "xlsx";
import { format } from "date-fns";
import {
  FileSpreadsheet,
  FileDown,
  Users,
  CalendarDays,
  Loader2,
  BarChart3,
  AlertCircle,
  LayoutList,
  UserCheck,
  ListChecks,
  Info,
} from "lucide-react";
import { createClient } from "@/utils/supabase/client";
import { cn } from "@/lib/utils";

// ── Period types ──────────────────────────────────────────────────────────────

type PeriodKey = "day" | "week" | "month" | "custom";

type DateRange = { start: string; end: string } | null;

function getRange(
  period: PeriodKey,
  customFrom: string,
  customTo: string,
): DateRange {
  const now   = new Date();
  const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());

  switch (period) {
    case "day":
      return { start: today.toISOString(), end: now.toISOString() };
    case "week": {
      const d = new Date(today);
      d.setDate(d.getDate() - 7);
      return { start: d.toISOString(), end: now.toISOString() };
    }
    case "month":
      return {
        start: new Date(now.getFullYear(), now.getMonth(), 1).toISOString(),
        end:   now.toISOString(),
      };
    case "custom":
      if (!customFrom || !customTo) return null;
      return {
        start: new Date(customFrom).toISOString(),
        end:   new Date(`${customTo}T23:59:59`).toISOString(),
      };
  }
}

// ── Helpers ───────────────────────────────────────────────────────────────────

/** Download a file generated by SheetJS */
function downloadFile(
  ws: XLSX.WorkSheet,
  filename: string,
  format_: "xlsx" | "csv",
) {
  if (format_ === "xlsx") {
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, "Reporte");
    XLSX.writeFile(wb, `${filename}.xlsx`);
  } else {
    // UTF-8 BOM so Excel opens CSV with correct encoding
    const bom  = "\ufeff";
    const csv  = XLSX.utils.sheet_to_csv(ws, { FS: "," });
    const blob = new Blob([bom + csv], { type: "text/csv;charset=utf-8;" });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement("a");
    a.href     = url;
    a.download = `${filename}.csv`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }
}

// ── Period Picker ─────────────────────────────────────────────────────────────

interface PeriodPickerProps {
  period:       PeriodKey;
  customFrom:   string;
  customTo:     string;
  onPeriod:     (p: PeriodKey) => void;
  onCustomFrom: (v: string) => void;
  onCustomTo:   (v: string) => void;
  t:            ReturnType<typeof useTranslations>;
}

function PeriodPicker({
  period,
  customFrom,
  customTo,
  onPeriod,
  onCustomFrom,
  onCustomTo,
  t,
}: PeriodPickerProps) {
  const chips: PeriodKey[] = ["day", "week", "month", "custom"];

  return (
    <div className="space-y-3">
      {/* Chips */}
      <div className="flex flex-wrap gap-2">
        {chips.map((key) => (
          <button
            key={key}
            type="button"
            onClick={() => onPeriod(key)}
            className={cn(
              "px-3 py-1.5 rounded-xl border text-xs font-semibold font-roboto transition-all",
              period === key
                ? "bg-secondary text-white border-secondary shadow-sm"
                : "bg-white text-gray-600 border-gray-200 hover:border-secondary/40",
            )}
          >
            {t(`period_${key}` as Parameters<typeof t>[0])}
          </button>
        ))}
      </div>

      {/* Custom date pickers */}
      {period === "custom" && (
        <div className="flex flex-col sm:flex-row gap-3">
          <div className="flex-1 space-y-1">
            <label className="text-[10px] font-semibold uppercase tracking-widest text-gray-400">
              {t("fieldDesde")}
            </label>
            <input
              type="date"
              value={customFrom}
              max={customTo || undefined}
              onChange={(e) => onCustomFrom(e.target.value)}
              className="w-full px-3 py-2 rounded-xl border border-gray-200 text-sm font-roboto text-gray-800
                         focus:outline-none focus:ring-2 focus:ring-secondary/30 focus:border-secondary transition"
            />
          </div>
          <div className="flex-1 space-y-1">
            <label className="text-[10px] font-semibold uppercase tracking-widest text-gray-400">
              {t("fieldHasta")}
            </label>
            <input
              type="date"
              value={customTo}
              min={customFrom || undefined}
              onChange={(e) => onCustomTo(e.target.value)}
              className="w-full px-3 py-2 rounded-xl border border-gray-200 text-sm font-roboto text-gray-800
                         focus:outline-none focus:ring-2 focus:ring-secondary/30 focus:border-secondary transition"
            />
          </div>
        </div>
      )}
    </div>
  );
}

// ── Export Buttons ─────────────────────────────────────────────────────────────

interface ExportButtonsProps {
  onExport:  (fmt: "xlsx" | "csv") => void;
  exporting: boolean;
  disabled:  boolean;
  t:         ReturnType<typeof useTranslations>;
}

function ExportButtons({ onExport, exporting, disabled, t }: ExportButtonsProps) {
  return (
    <div className="flex gap-2">
      <button
        type="button"
        onClick={() => onExport("xlsx")}
        disabled={disabled || exporting}
        className="flex items-center gap-1.5 px-4 py-2 rounded-xl bg-emerald-600 text-white
                   text-xs font-semibold font-roboto hover:bg-emerald-700
                   disabled:opacity-40 disabled:cursor-not-allowed transition-colors"
      >
        {exporting
          ? <Loader2 className="w-3.5 h-3.5 animate-spin" />
          : <FileSpreadsheet className="w-3.5 h-3.5" />
        }
        Excel (.xlsx)
      </button>
      <button
        type="button"
        onClick={() => onExport("csv")}
        disabled={disabled || exporting}
        className="flex items-center gap-1.5 px-4 py-2 rounded-xl bg-white text-gray-700
                   border border-gray-200 text-xs font-semibold font-roboto
                   hover:bg-gray-50 hover:border-gray-300
                   disabled:opacity-40 disabled:cursor-not-allowed transition-colors"
      >
        {exporting
          ? <Loader2 className="w-3.5 h-3.5 animate-spin" />
          : <FileDown className="w-3.5 h-3.5" />
        }
        CSV
      </button>
    </div>
  );
}

// ── Record count badge ────────────────────────────────────────────────────────

function CountBadge({
  loading,
  error,
  count,
  t,
}: {
  loading: boolean;
  error:   boolean;
  count:   number;
  t:       ReturnType<typeof useTranslations>;
}) {
  if (loading) {
    return <div className="h-5 w-32 bg-gray-200 rounded animate-pulse" />;
  }
  if (error) {
    return (
      <span className="flex items-center gap-1 text-xs font-roboto text-red-500">
        <AlertCircle className="w-3.5 h-3.5" />
        {t("errorFetch")}
      </span>
    );
  }
  return (
    <span className={cn(
      "text-xs font-roboto font-medium",
      count === 0 ? "text-neutral/60" : "text-secondary",
    )}>
      {count === 0
        ? t("emptyReport")
        : t("totalRegistros", { count })}
    </span>
  );
}

// ── Report 1: Usuarios Nuevos ─────────────────────────────────────────────────

type UsuarioRow = {
  nombre_completo:     string | null;
  email:               string | null;
  telefono:            string | null;
  rol:                 string;
  tipo_cuenta:         string;
  estado:              string;
  created_at:          string;
};

function ReporteUsuarios() {
  const t = useTranslations("Dashboard.empresa.reportes");

  const [period,     setPeriod]     = useState<PeriodKey>("month");
  const [customFrom, setCustomFrom] = useState("");
  const [customTo,   setCustomTo]   = useState("");
  const [data,       setData]       = useState<UsuarioRow[]>([]);
  const [loading,    setLoading]    = useState(false);
  const [error,      setError]      = useState(false);
  const [exporting,  setExporting]  = useState(false);

  const range = getRange(period, customFrom, customTo);

  // ── Auto-fetch when range is valid ──────────────────────────────────────
  const fetchData = useCallback(async (r: DateRange) => {
    if (!r) return;
    setLoading(true);
    setError(false);

    const supabase = createClient();
    const { data: rows, error: err } = await supabase
      .from("users")
      .select("nombre_completo, email, telefono, rol, tipo_cuenta, estado, created_at")
      .gte("created_at", r.start)
      .lte("created_at", r.end)
      .order("created_at", { ascending: false });

    if (err || !rows) {
      setError(true);
    } else {
      setData(rows as UsuarioRow[]);
    }
    setLoading(false);
  }, []);

  useEffect(() => {
    const r = getRange(period, customFrom, customTo);
    fetchData(r);
  }, [period, customFrom, customTo, fetchData]);

  // ── Export ───────────────────────────────────────────────────────────────
  async function handleExport(fmt: "xlsx" | "csv") {
    if (!range || data.length === 0) return;
    setExporting(true);

    try {
      const rows = data.map((u) => ({
        [t("colNombre")]:      u.nombre_completo    ?? "—",
        [t("colEmail")]:       u.email              ?? "—",
        [t("colTelefono")]:    u.telefono           ?? "—",
        [t("colRol")]:         u.rol,
        [t("colTipoCuenta")]:  u.tipo_cuenta,
        [t("colEstado")]:      u.estado,
        [t("colFechaRegistro")]: format(new Date(u.created_at), "dd/MM/yyyy HH:mm"),
      }));

      const ws = XLSX.utils.json_to_sheet(rows);
      downloadFile(ws, `reporte_usuarios_${format(new Date(), "yyyyMMdd_HHmm")}`, fmt);
      toast.success(t("successExport"));
    } catch {
      toast.error(t("errorExport"));
    }
    setExporting(false);
  }

  const canExport = !!range && !loading && !error && data.length > 0;

  return (
    <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden">
      {/* Header */}
      <div className="flex items-start gap-3 px-5 py-4 border-b border-gray-50">
        <div className="mt-0.5 p-1.5 rounded-lg bg-secondary/5">
          <Users className="w-4 h-4 text-secondary" />
        </div>
        <div>
          <h3 className="font-poppins font-semibold text-sm text-gray-900">
            {t("sectionUsuarios")}
          </h3>
          <p className="text-xs font-roboto text-neutral/60 mt-0.5">
            {t("sectionUsuariosSubtitle")}
          </p>
        </div>
      </div>

      {/* Description banner */}
      <div className="flex items-start gap-2 px-5 pt-4 pb-0">
        <Info className="w-3.5 h-3.5 text-secondary/70 mt-0.5 shrink-0" />
        <p className="text-xs font-roboto text-neutral/70 leading-relaxed">
          {t("sectionUsuariosDesc")}
        </p>
      </div>

      {/* Body */}
      <div className="p-5 space-y-5">
        <PeriodPicker
          period={period}
          customFrom={customFrom}
          customTo={customTo}
          onPeriod={setPeriod}
          onCustomFrom={setCustomFrom}
          onCustomTo={setCustomTo}
          t={t}
        />

        {/* Count + export */}
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
          <CountBadge loading={loading} error={error} count={data.length} t={t} />
          <ExportButtons
            onExport={handleExport}
            exporting={exporting}
            disabled={!canExport}
            t={t}
          />
        </div>
      </div>
    </div>
  );
}

// ── Report 2: Citas ───────────────────────────────────────────────────────────

type CitaRaw = {
  paciente: {
    id:          string;
    nombre_completo: string | null;
    tipo_cuenta: string;
    titular_id:  string | null;
  } | null;
};

type ServicioMap = Map<string, number>;
type TitularMap  = Map<string, { nombre: string; propias: number; familiares: number }>;

type CitasMode = "servicio" | "titular";

function ReporteCitas() {
  const t = useTranslations("Dashboard.empresa.reportes");

  const [period,     setPeriod]     = useState<PeriodKey>("month");
  const [customFrom, setCustomFrom] = useState("");
  const [customTo,   setCustomTo]   = useState("");
  const [mode,       setMode]       = useState<CitasMode>("servicio");

  // Raw citas rows + aggregated maps
  const [rawCitas,    setRawCitas]    = useState<CitaRaw[]>([]);
  const [servicios,   setServicios]   = useState<ServicioMap>(new Map());
  const [titulares,   setTitulares]   = useState<TitularMap>(new Map());
  const [loading,     setLoading]     = useState(false);
  const [error,       setError]       = useState(false);
  const [exporting,   setExporting]   = useState(false);

  const range = getRange(period, customFrom, customTo);

  // ── Fetch citas + titulares for period ───────────────────────────────────
  const fetchData = useCallback(async (r: DateRange) => {
    if (!r) return;
    setLoading(true);
    setError(false);

    const supabase = createClient();

    // Fetch citas with paciente join AND service name
    const [citasResult, titularesResult] = await Promise.all([
      supabase
        .from("citas")
        .select(`
          servicio:servicios!citas_ea_service_id_fkey(nombre),
          paciente:users!paciente_id(id, nombre_completo, tipo_cuenta, titular_id)
        `)
        .gte("fecha_hora_cita", r.start)
        .lte("fecha_hora_cita", r.end),

      // Titulares for name lookup when grouping familiares
      supabase
        .from("users")
        .select("id, nombre_completo")
        .eq("tipo_cuenta", "titular"),
    ]);

    if (citasResult.error || titularesResult.error) {
      setError(true);
      setLoading(false);
      return;
    }

    const rows    = (citasResult.data   ?? []) as unknown as (CitaRaw & { servicio: { nombre: string } | null })[];
    const titRows = (titularesResult.data ?? []) as { id: string; nombre_completo: string | null }[];

    setRawCitas(rows as CitaRaw[]);

    // ── Aggregate: por servicio ─────────────────────────────────────────
    const svcMap: ServicioMap = new Map();
    for (const row of rows) {
      const name = (row.servicio as { nombre: string } | null)?.nombre ?? t("sinServicio");
      svcMap.set(name, (svcMap.get(name) ?? 0) + 1);
    }
    setServicios(svcMap);

    // ── Aggregate: por titular ──────────────────────────────────────────
    // Build lookup: titularId → nombre
    const titNameMap = new Map(titRows.map((r) => [r.id, r.nombre_completo ?? "—"]));

    const titMap: TitularMap = new Map();

    for (const row of rows) {
      const p = row.paciente as CitaRaw["paciente"];
      if (!p) continue;

      if (p.tipo_cuenta === "titular") {
        const entry = titMap.get(p.id) ?? { nombre: p.nombre_completo ?? "—", propias: 0, familiares: 0 };
        entry.propias++;
        titMap.set(p.id, entry);
      } else if (p.tipo_cuenta === "familiar" && p.titular_id) {
        const titNombre = titNameMap.get(p.titular_id) ?? "—";
        const entry     = titMap.get(p.titular_id) ?? { nombre: titNombre, propias: 0, familiares: 0 };
        entry.familiares++;
        titMap.set(p.titular_id, entry);
      }
    }
    setTitulares(titMap);
    setLoading(false);
  }, [t]);

  useEffect(() => {
    const r = getRange(period, customFrom, customTo);
    fetchData(r);
  }, [period, customFrom, customTo, fetchData]);

  // ── Export ───────────────────────────────────────────────────────────────
  async function handleExport(fmt: "xlsx" | "csv") {
    if (!range) return;
    setExporting(true);

    try {
      let ws: XLSX.WorkSheet;
      let filename: string;

      if (mode === "servicio") {
        const rows = Array.from(servicios.entries())
          .sort((a, b) => b[1] - a[1])
          .map(([servicio, total]) => ({
            [t("colServicio")]:   servicio,
            [t("colTotalCitas")]: total,
          }));
        ws       = XLSX.utils.json_to_sheet(rows);
        filename = `reporte_citas_servicio_${format(new Date(), "yyyyMMdd_HHmm")}`;
      } else {
        const rows = Array.from(titulares.entries())
          .sort((a, b) => (b[1].propias + b[1].familiares) - (a[1].propias + a[1].familiares))
          .map(([, d]) => ({
            [t("colTitular")]:           d.nombre,
            [t("colCitasPropias")]:      d.propias,
            [t("colCitasFamiliares")]:   d.familiares,
            [t("colTotal")]:             d.propias + d.familiares,
          }));
        ws       = XLSX.utils.json_to_sheet(rows);
        filename = `reporte_citas_titular_${format(new Date(), "yyyyMMdd_HHmm")}`;
      }

      downloadFile(ws, filename, fmt);
      toast.success(t("successExport"));
    } catch {
      toast.error(t("errorExport"));
    }
    setExporting(false);
  }

  const count     = mode === "servicio" ? rawCitas.length : titulares.size;
  const canExport = !!range && !loading && !error && count > 0;

  return (
    <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden">
      {/* Header */}
      <div className="flex items-start gap-3 px-5 py-4 border-b border-gray-50">
        <div className="mt-0.5 p-1.5 rounded-lg bg-secondary/5">
          <CalendarDays className="w-4 h-4 text-secondary" />
        </div>
        <div>
          <h3 className="font-poppins font-semibold text-sm text-gray-900">
            {t("sectionCitas")}
          </h3>
          <p className="text-xs font-roboto text-neutral/60 mt-0.5">
            {t("sectionCitasSubtitle")}
          </p>
        </div>
      </div>

      {/* Description banner */}
      <div className="flex items-start gap-2 px-5 pt-4 pb-0">
        <Info className="w-3.5 h-3.5 text-secondary/70 mt-0.5 shrink-0" />
        <p className="text-xs font-roboto text-neutral/70 leading-relaxed">
          {t("sectionCitasDesc")}
        </p>
      </div>

      {/* Body */}
      <div className="p-5 space-y-5">
        <PeriodPicker
          period={period}
          customFrom={customFrom}
          customTo={customTo}
          onPeriod={setPeriod}
          onCustomFrom={setCustomFrom}
          onCustomTo={setCustomTo}
          t={t}
        />

        {/* Mode toggle: Por servicio / Por titular */}
        <div className="space-y-1.5">
          <p className="text-[10px] font-semibold uppercase tracking-widest text-gray-400">
            {t("labelAgrupar")}
          </p>
          <div className="flex rounded-xl border border-gray-200 overflow-hidden w-fit">
            <button
              type="button"
              onClick={() => setMode("servicio")}
              className={cn(
                "flex items-center gap-1.5 px-4 py-2 text-xs font-semibold font-roboto transition-colors",
                mode === "servicio"
                  ? "bg-secondary text-white"
                  : "bg-white text-gray-500 hover:bg-gray-50",
              )}
            >
              <LayoutList className="w-3.5 h-3.5" />
              {t("modeServicio")}
            </button>
            <button
              type="button"
              onClick={() => setMode("titular")}
              className={cn(
                "flex items-center gap-1.5 px-4 py-2 text-xs font-semibold font-roboto border-l border-gray-200 transition-colors",
                mode === "titular"
                  ? "bg-secondary text-white"
                  : "bg-white text-gray-500 hover:bg-gray-50",
              )}
            >
              <UserCheck className="w-3.5 h-3.5" />
              {t("modeTitular")}
            </button>
          </div>
        </div>

        {/* Count + export */}
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
          <CountBadge loading={loading} error={error} count={count} t={t} />
          <ExportButtons
            onExport={handleExport}
            exporting={exporting}
            disabled={!canExport}
            t={t}
          />
        </div>
      </div>
    </div>
  );
}

// ── Report 3: Utilización de Contratos ───────────────────────────────────────

type ContratoPeriodKey = "10d" | "15d" | "1m" | "custom";

function getContratoRange(
  period: ContratoPeriodKey,
  startDate: string,
  endDate: string,
): DateRange {
  const now = new Date();
  if (period === "custom") {
    if (!startDate || !endDate) return null;
    return {
      start: new Date(startDate).toISOString(),
      end:   new Date(`${endDate}T23:59:59`).toISOString(),
    };
  }
  if (!startDate) return null;
  const start = new Date(startDate);
  const end   = new Date(start);
  if (period === "10d")     end.setDate(end.getDate() + 10);
  else if (period === "15d") end.setDate(end.getDate() + 15);
  else                       end.setMonth(end.getMonth() + 1);
  return { start: start.toISOString(), end: (end > now ? now : end).toISOString() };
}

type CsRawRow = {
  id:                string;
  contrato_id:       string;
  cuota_por_titular: number;
  servicio_id:       string;
};

type CitaContratoRaw = {
  id:                   string;
  contrato_servicio_id: string | null;
  paciente: {
    id:              string;
    nombre_completo: string | null;
    tipo_cuenta:     string;
    titular_id:      string | null;
  } | null;
};

type ContratoServicioRow = {
  csId:           string;
  contratoNombre: string;
  servicioNombre: string;
  cuotaTitular:   number;
  citasUsadas:    number;
};

type TitularContratoRow = {
  titularId:      string;
  titularNombre:  string;
  contratoNombre: string;
  servicioNombre: string;
  propias:        number;
  familiares:     number;
};

type ContratoMode = "contrato" | "titular";

function ReporteContratos() {
  const t = useTranslations("Dashboard.empresa.reportes");

  const defaultStart = format(new Date(Date.now() - 10 * 24 * 3600 * 1000), "yyyy-MM-dd");

  const [period,    setPeriod]    = useState<ContratoPeriodKey>("10d");
  const [startDate, setStartDate] = useState(defaultStart);
  const [endDate,   setEndDate]   = useState(format(new Date(), "yyyy-MM-dd"));
  const [mode,      setMode]      = useState<ContratoMode>("contrato");

  const [csRows,      setCsRows]      = useState<ContratoServicioRow[]>([]);
  const [titularRows, setTitularRows] = useState<TitularContratoRow[]>([]);
  const [loading,     setLoading]     = useState(false);
  const [error,       setError]       = useState(false);
  const [exporting,   setExporting]   = useState(false);

  const range = getContratoRange(period, startDate, endDate);

  const fetchData = useCallback(async (r: DateRange) => {
    if (!r) return;
    setLoading(true);
    setError(false);

    const supabase = createClient();

    const [csResult, citasResult] = await Promise.all([
      supabase.from("contrato_servicios").select("id, contrato_id, cuota_por_titular, servicio_id"),
      supabase
        .from("citas")
        .select("id, contrato_servicio_id, paciente:users!paciente_id(id, nombre_completo, tipo_cuenta, titular_id)")
        .not("contrato_servicio_id", "is", null)
        .gte("fecha_hora_cita", r.start)
        .lte("fecha_hora_cita", r.end),
    ]);

    if (csResult.error || citasResult.error) {
      setError(true);
      setLoading(false);
      return;
    }

    const css   = (csResult.data ?? []) as CsRawRow[];
    const citas = (citasResult.data ?? []) as unknown as CitaContratoRaw[];

    const contratoIds = [...new Set(css.map((c) => c.contrato_id).filter(Boolean))];
    const serviceIds  = [...new Set(css.map((c) => c.servicio_id).filter(Boolean))];

    if (contratoIds.length === 0) {
      setCsRows([]);
      setTitularRows([]);
      setLoading(false);
      return;
    }

    const [contratosRes, serviciosRes] = await Promise.all([
      supabase.from("contratos").select("id, nombre").in("id", contratoIds),
      supabase.from("servicios").select("id, nombre").in("id", serviceIds),
    ]);

    const contratoMap = new Map((contratosRes.data ?? []).map((c) => [c.id, c.nombre as string]));
    const servicioMap = new Map((serviciosRes.data ?? []).map((s) => [s.id, s.nombre as string]));
    const csMap       = new Map(css.map((cs) => [cs.id, cs]));

    // ── Aggregate: por contrato-servicio ─────────────────────────────────
    const csCountMap = new Map<string, number>();
    for (const cita of citas) {
      if (!cita.contrato_servicio_id) continue;
      csCountMap.set(cita.contrato_servicio_id, (csCountMap.get(cita.contrato_servicio_id) ?? 0) + 1);
    }

    setCsRows(
      css
        .map((cs) => ({
          csId:           cs.id,
          contratoNombre: contratoMap.get(cs.contrato_id) ?? "—",
          servicioNombre: servicioMap.get(cs.servicio_id) ?? "—",
          cuotaTitular:   cs.cuota_por_titular,
          citasUsadas:    csCountMap.get(cs.id) ?? 0,
        }))
        .filter((r) => r.citasUsadas > 0)
        .sort((a, b) => b.citasUsadas - a.citasUsadas),
    );

    // ── Aggregate: por titular ────────────────────────────────────────────
    const titMap = new Map<string, TitularContratoRow>();

    for (const cita of citas) {
      if (!cita.contrato_servicio_id || !cita.paciente) continue;
      const cs = csMap.get(cita.contrato_servicio_id);
      if (!cs) continue;

      const p              = cita.paciente;
      const contratoNombre = contratoMap.get(cs.contrato_id) ?? "—";
      const servicioNombre = servicioMap.get(cs.servicio_id) ?? "—";
      const titId          = p.tipo_cuenta === "titular" ? p.id : (p.titular_id ?? null);
      if (!titId) continue;

      const key   = `${titId}::${cita.contrato_servicio_id}`;
      const entry = titMap.get(key) ?? {
        titularId:     titId,
        titularNombre: p.tipo_cuenta === "titular" ? (p.nombre_completo ?? "—") : "—",
        contratoNombre,
        servicioNombre,
        propias:    0,
        familiares: 0,
      };

      if (p.tipo_cuenta === "titular") {
        entry.titularNombre = p.nombre_completo ?? entry.titularNombre;
        entry.propias++;
      } else {
        entry.familiares++;
      }
      titMap.set(key, entry);
    }

    // Backfill titular names that came from familiar citas
    const missingIds = [...titMap.values()]
      .filter((r) => r.titularNombre === "—")
      .map((r) => r.titularId);

    if (missingIds.length > 0) {
      const { data: titularNames } = await supabase
        .from("users")
        .select("id, nombre_completo")
        .in("id", missingIds);
      const nameMap = new Map((titularNames ?? []).map((u) => [u.id, u.nombre_completo as string]));
      for (const row of titMap.values()) {
        if (row.titularNombre === "—") row.titularNombre = nameMap.get(row.titularId) ?? "—";
      }
    }

    setTitularRows(
      [...titMap.values()].sort((a, b) => (b.propias + b.familiares) - (a.propias + a.familiares)),
    );
    setLoading(false);
  }, []);

  useEffect(() => {
    fetchData(getContratoRange(period, startDate, endDate));
  }, [period, startDate, endDate, fetchData]);

  function handlePeriodChip(p: ContratoPeriodKey) {
    setPeriod(p);
    if (p !== "custom") {
      const d = new Date();
      if (p === "10d") d.setDate(d.getDate() - 10);
      else if (p === "15d") d.setDate(d.getDate() - 15);
      else d.setMonth(d.getMonth() - 1);
      setStartDate(format(d, "yyyy-MM-dd"));
      setEndDate(format(new Date(), "yyyy-MM-dd"));
    }
  }

  async function handleExport(fmt: "xlsx" | "csv") {
    if (!range) return;
    setExporting(true);
    try {
      let ws: XLSX.WorkSheet;
      let filename: string;

      if (mode === "contrato") {
        const rows = csRows.map((r) => ({
          [t("colContrato")]:    r.contratoNombre,
          [t("colServicio")]:    r.servicioNombre,
          [t("colCuotaTitular")]: r.cuotaTitular,
          [t("colCitasUsadas")]: r.citasUsadas,
        }));
        ws       = XLSX.utils.json_to_sheet(rows);
        filename = `reporte_contratos_servicio_${format(new Date(), "yyyyMMdd_HHmm")}`;
      } else {
        const rows = titularRows.map((r) => ({
          [t("colTitular")]:          r.titularNombre,
          [t("colContrato")]:          r.contratoNombre,
          [t("colServicio")]:          r.servicioNombre,
          [t("colCitasPropias")]:      r.propias,
          [t("colCitasFamiliares")]:   r.familiares,
          [t("colTotal")]:             r.propias + r.familiares,
        }));
        ws       = XLSX.utils.json_to_sheet(rows);
        filename = `reporte_contratos_titular_${format(new Date(), "yyyyMMdd_HHmm")}`;
      }

      downloadFile(ws, filename, fmt);
      toast.success(t("successExport"));
    } catch {
      toast.error(t("errorExport"));
    }
    setExporting(false);
  }

  const count     = mode === "contrato" ? csRows.length : titularRows.length;
  const canExport = !!range && !loading && !error && count > 0;

  const CHIPS: ContratoPeriodKey[] = ["10d", "15d", "1m", "custom"];

  return (
    <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden">
      <div className="flex items-start gap-3 px-5 py-4 border-b border-gray-50">
        <div className="mt-0.5 p-1.5 rounded-lg bg-secondary/5">
          <ListChecks className="w-4 h-4 text-secondary" />
        </div>
        <div>
          <h3 className="font-poppins font-semibold text-sm text-gray-900">
            {t("sectionContratos")}
          </h3>
          <p className="text-xs font-roboto text-neutral/60 mt-0.5">
            {t("sectionContratosSubtitle")}
          </p>
        </div>
      </div>

      {/* Description banner */}
      <div className="flex items-start gap-2 px-5 pt-4 pb-0">
        <Info className="w-3.5 h-3.5 text-secondary/70 mt-0.5 shrink-0" />
        <p className="text-xs font-roboto text-neutral/70 leading-relaxed">
          {t("sectionContratosDesc")}
        </p>
      </div>

      <div className="p-5 space-y-5">
        {/* Period chips + date inputs */}
        <div className="space-y-3">
          <div className="flex flex-wrap gap-2">
            {CHIPS.map((key) => (
              <button
                key={key}
                type="button"
                onClick={() => handlePeriodChip(key)}
                className={cn(
                  "px-3 py-1.5 rounded-xl border text-xs font-semibold font-roboto transition-all",
                  period === key
                    ? "bg-secondary text-white border-secondary shadow-sm"
                    : "bg-white text-gray-600 border-gray-200 hover:border-secondary/40",
                )}
              >
                {t(`period_${key}` as Parameters<typeof t>[0])}
              </button>
            ))}
          </div>

          {period !== "custom" && (
            <div className="space-y-1">
              <label className="text-[10px] font-semibold uppercase tracking-widest text-gray-400">
                {t("fieldFechaInicio")}
              </label>
              <input
                type="date"
                value={startDate}
                onChange={(e) => setStartDate(e.target.value)}
                className="px-3 py-2 rounded-xl border border-gray-200 text-sm font-roboto text-gray-800
                           focus:outline-none focus:ring-2 focus:ring-secondary/30 focus:border-secondary transition"
              />
            </div>
          )}

          {period === "custom" && (
            <div className="flex flex-col sm:flex-row gap-3">
              <div className="flex-1 space-y-1">
                <label className="text-[10px] font-semibold uppercase tracking-widest text-gray-400">
                  {t("fieldDesde")}
                </label>
                <input
                  type="date"
                  value={startDate}
                  max={endDate || undefined}
                  onChange={(e) => setStartDate(e.target.value)}
                  className="w-full px-3 py-2 rounded-xl border border-gray-200 text-sm font-roboto text-gray-800
                             focus:outline-none focus:ring-2 focus:ring-secondary/30 focus:border-secondary transition"
                />
              </div>
              <div className="flex-1 space-y-1">
                <label className="text-[10px] font-semibold uppercase tracking-widest text-gray-400">
                  {t("fieldHasta")}
                </label>
                <input
                  type="date"
                  value={endDate}
                  min={startDate || undefined}
                  onChange={(e) => setEndDate(e.target.value)}
                  className="w-full px-3 py-2 rounded-xl border border-gray-200 text-sm font-roboto text-gray-800
                             focus:outline-none focus:ring-2 focus:ring-secondary/30 focus:border-secondary transition"
                />
              </div>
            </div>
          )}
        </div>

        {/* Mode toggle */}
        <div className="space-y-1.5">
          <p className="text-[10px] font-semibold uppercase tracking-widest text-gray-400">
            {t("labelAgrupar")}
          </p>
          <div className="flex rounded-xl border border-gray-200 overflow-hidden w-fit">
            <button
              type="button"
              onClick={() => setMode("contrato")}
              className={cn(
                "flex items-center gap-1.5 px-4 py-2 text-xs font-semibold font-roboto transition-colors",
                mode === "contrato"
                  ? "bg-secondary text-white"
                  : "bg-white text-gray-500 hover:bg-gray-50",
              )}
            >
              <LayoutList className="w-3.5 h-3.5" />
              {t("modeContrato")}
            </button>
            <button
              type="button"
              onClick={() => setMode("titular")}
              className={cn(
                "flex items-center gap-1.5 px-4 py-2 text-xs font-semibold font-roboto border-l border-gray-200 transition-colors",
                mode === "titular"
                  ? "bg-secondary text-white"
                  : "bg-white text-gray-500 hover:bg-gray-50",
              )}
            >
              <UserCheck className="w-3.5 h-3.5" />
              {t("modeTitular")}
            </button>
          </div>
        </div>

        {/* Count + export */}
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
          <CountBadge loading={loading} error={error} count={count} t={t} />
          <ExportButtons onExport={handleExport} exporting={exporting} disabled={!canExport} t={t} />
        </div>
      </div>
    </div>
  );
}

// ── Main page component ───────────────────────────────────────────────────────

export default function EmpresaReportes() {
  const t = useTranslations("Dashboard.empresa.reportes");

  return (
    <div className="space-y-6">
      {/* Page header */}
      <div>
        <div className="flex items-center gap-2.5 mb-1">
          <BarChart3 className="w-5 h-5 text-secondary" />
          <h1 className="text-2xl font-poppins font-bold text-gray-900">{t("titulo")}</h1>
        </div>
        <p className="text-sm font-roboto text-neutral">{t("subtitle")}</p>
      </div>

      {/* Report cards */}
      <ReporteUsuarios />
      <ReporteCitas />
      <ReporteContratos />
    </div>
  );
}
